name: "Container Memory"
description: "Outputs the container memory information"
inputs:
  recipient: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  memory: # id of output
    description: 'Memory information of container'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.recipient }}
